
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvwshjngwvjrzpgwvvkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2d3Noam5nd3ZqcnpwZ3d2dmt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTYzOTQsImV4cCI6MjA2NjgzMjM5NH0.Tea-hBTj2pTbyA3Y3XuqIvMBEzO5rvYs0WFWdB_QPbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
